import React from 'react';
import type { Metadata } from 'next';
import '../public/globals.css';

interface Props {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className="flex flex-col h-screen bg-gray-600">{children}</body>
    </html>
  );
}
